### ISSUE TITLE
Code Cleanup Tracker 2020

### ISSUE THREAD

**Issue by octylFractal** [EngineHub/WorldEdit#1412]
The codebase has some minor issues which keep bugging me in IntelliJ/PRs.

- [x] Add `final` to all fields which should have it
- [x] Add more checkstyle rules to align the formatting of the codebase together.
- [x] Replace all `\r\n` with `\n\`, except in `gradlew.bat` :P
